# Default values for busyidle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: danacr.azurecr.io/busyidle
  tag: VERSION
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 1000m
    memory: 550Mi
  requests:
    cpu: 100m
    memory: 550Mi

nodeSelector: {}

tolerations: []

affinity: {}
